---
- name: 'restart stunnel'
  service:
    name: "{{ ldap_client_stunnel_service_name }}"
    state: "{{ ansible_facts['is_chroot'] | ternary(omit, 'restarted') }}"

- name: 'reload stunnel'
  service:
    name: "{{ ldap_client_stunnel_service_name }}"
    state: "{{ ansible_facts['is_chroot'] | ternary(omit, 'reloaded') }}"
